using System;

namespace API.DTOs
{
    public class MessageDto
    {
        public int Id { get; set; } // each message generated by DB
        public int SenderId { get; set; }
        public string SenderUsername { get; set; }

        // relationship between app user and the message

        public string SenderPhotoUrl { get; set; } // replaced app user
        public int RecipientId { get; set; }
        public string RecipientUsername { get; set; }
        public string RecipientPhotoUrl { get; set; } //replaced app user

        // message specific properties
        public string Content { get; set; }
        public DateTime? DateRead { get; set; } // optional to be null if not read
        public DateTime MessageSent { get; set; } 

        
    }
}